store/account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from . import views
from .forms import PasswordChangeForm

urlpatterns = patterns(
    '',
    url(r'^login/$', auth_views.login, name='login',
        kwargs={'template_name': 'account/login.html'}),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'template_name': 'account/logged_out.html'}),
    url(r'^password_change/$', auth_views.password_change, name='password_change',
        kwargs={'template_name': 'account/password_change.html',
                'post_change_redirect': 'done/',
                'password_change_form': PasswordChangeForm}),
    url(r'^password_change/done/$', auth_views.password_change_done,
        name='password_change_done',
        kwargs={'template_name': 'account/password_change_done.html'}),

    url(r'^profile/$', views.profile, name='profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/done/$', views.register_done, name='register_done'),
    url(r'^profile/update/$', views.profile_change, name='profile_change'),
)

store/admin/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.overview, name='overview'),

    url(r'^category/', include('category_admin.urls', namespace='category')),
    url(r'^product/', include('product_admin.urls', namespace='product')),
    url(r'^account/', include('account_admin.urls', namespace='account')),
    url(r'order/', include('order_admin.urls', namespace='order')),

)

store/cart/urls.py
from django.conf.urls import patterns, url

from cart import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

store/order/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.create, name='create'),
    url(r'^current/$', views.CurrentView.as_view(), name='current'),
    url(r'^past/$', views.PastView.as_view(), name='past'),
    url(r'^(?P<order_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<order_id>\d+)/done/', views.done, name='done'),
)

store/store/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'store.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'store.views.home', name='home'),
    url('^about/$', 'store.views.about', name='about'),

    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^admin/', include('admin.urls', namespace='admin')),

    # RESTful APIs.
    url(r'^api/cart/', include('cart.urls_api', namespace='cart_api')),
    url(r'^api/order/', include('order.urls_api', namespace='order_api')),

    # url(r'^admin/', include(admin.site.urls)),

)


# Serving media (user-uploaded) files by Django.
# This should only be used in development environment.
# HTTP server should be configured to serve them directly in product environment.

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/store/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'store/home.html')


def about(request):
    return render(request, 'store/about.html')

store/store/templates/store/about.html
{% extends "store/front-base.html" %}
{% block title %}Categories{% endblock %}

{% block head %}
  <style>
  article p { font-size: 1.2em; color: #333; }

  </style>
{% endblock %}

{% block main %}

  <h1 class="page-header">About</h1>
  <article class="row">
    <div class="col-md-8">
      <h2>CFMQ</h2>
      <p>CFMQ stands for <em>Chenfan and Moquan</em></p>
      <p>This website can communicate with UPS and Warehouse to buy and products</p>

      <h2>CFMQ</h2>
      <p>The website is designed by Chenfan Li and Moquan Jiang for ece590.</p>
      
    </div>
  </article>

{% endblock %}

store/store/templates/store/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ title }}{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link rel="stylesheet" href="{% static 'common.css' %}">
  {# TODO: Consider move jQuery to the bottom of page. #}
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>

  <!--[if lt IE 12]>
    <script src="{% static 'ie-patch.js' %}"></script>
  <![endif]-->
  {% block head %}
    {# Some additional per-page styles. #}
  {% endblock %}
</head>
<body>
  <div id="top-messages">
    <div id="remote-messages">
      {% bootstrap_messages %}
    </div>
    <!-- TODO: add a break line here -->
    <div id="local-messages">
      <div class="alert alert-dismissable template">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
      </div>
    </div>
  </div>

  {% block body %}
    {# Including main body with navigation bar and sidebar (if necessary). #}
  {% endblock %}

  <!-- Bootstrap -->
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

  <!-- jQuery.cookies: getting CSRF token -->
  <script src="{% static 'jquery.cookie/jquery.cookie.js' %}"></script>

  <script src="{% static 'common.js' %}"></script>

  {% block footer %}
    {# Some additional per-page scripts. #}
  {% endblock %}
</body>
</html>

store/store/templates/store/common-pagination.html
{% load args_string %}
<nav>
  <ul class="pagination">
  {% if list.has_previous %}
    <li class="previous">
      <a aria-label="Previous" href="{% args_string %}">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
  {% else %}
    <li class="previous disabled"><a aria-label="Previous" href="#">
      <span aria-hidden="true">&laquo;</span>
    </a></li>
  {% endif %}

  {% for page, current in list.neighbor_pages %}
    {% if not current %}
      <li><a href="{% args_string %}">{{ page }}</a></li>
    {% else %}
      <li class="active"><a href="#"><span class="sr-only">(current)</span>{{ page }}</a></li>
    {% endif %}
  {% endfor %}

  {% if list.has_next %}
    <li class="next">
      <a aria-label="Next" href="{% args_string %}">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  {% else %}
    <li class="next disabled"><a aria-label="Previous" href="#">
      <span aria-hidden="true">&raquo;</span>
    </a></li>
  {% endif %}
  </ul>
</nav>

store/store/templates/store/front-base-backup.html
{% extends "store/base.html" %}
{% load bootstrap3 %}

{# The template of all pages which are presented to customers.  #}

{% block body %}
<div class="container">
  <!-- Static navbar -->
  <!-- Reference: http://getbootstrap.com/examples/navbar/ -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ISI Store</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="nav-home"><a href="/">Home</a></li>
          <li class="nav-category"><a href="{% url 'category:index' %}">Categories</a></li>
          <li class="nav-about"><a href="{% url 'about' %}">About</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="nav-cart"><a href="{% url 'cart:index' %}"><span class="glyphicon glyphicon-shopping-cart"></span>
            Shopping Cart</a></li>
          <li class="dropdown nav-purchase">
            <a href="{% url 'order:index' %}" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-expanded="false"><span class="glyphicon glyphicon-usd"></span>
              Purchases <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'order:current' %}"><span class="glyphicon glyphicon-usd"></span>
                Current purchases</a></li>
              <li><a href="{% url 'order:past' %}"><span class="glyphicon glyphicon-ok-circle"></span>
                Past purchases</a></li>
            </ul>
          </li>
          <li class="dropdown nav-user">
            <a href="{% url 'order:index' %}" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>
                {% firstof user.get_short_name get_full_name get_username %}
              <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="dropdown-header">Profile</li>
              <li><a href="{% url 'account:profile' %}">View profile</a></li>
              <li><a href="{% url 'account:profile_change' %}">Update profile</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Account</li>
              <li><a href="{% url 'account:password_change' %}">Change password</a></li>
              <li><a href="{% url 'account:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-register"><a
              href="{% url 'account:register' %}?next={{ request.path }}">Register</a></li>
          <li class="nav-login"><a
              href="{% url 'account:login' %}?next={{ request.path }}">Log in</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>

  {% block main %}
    {# The main body #}
  {% endblock %}

  <footer>
    <hr>
    <p>COMP321 Information System Implementation</p>
  </footer>
</div><!--/.container -->
{% endblock %}

store/store/templates/store/front-base.html
{% extends "store/base.html" %}
{% load bootstrap3 %}

{# The template of all pages which are presented to customers.  #}

{% block body %}
<div class="container">
  <!-- Static navbar -->
  <!-- Reference: http://getbootstrap.com/examples/navbar/ -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">CFMQ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
	  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
	</li>
	<li class="nav-item active">
	  <a class="nav-link" href="{% url 'category:index' %}">Categories <span class="sr-only">(current)</span></a>
	</li>
	<li class="nav-item active">
	  <a class="nav-link" href="{% url 'about' %}">About <span class="sr-only">(current)</span></a>
	</li>
	{% if user.is_authenticated %}

	<li class="nav-item active"><a class="nav-link" href="{% url 'cart:index' %}"><span class="glyphicon glyphicon-shopping-cart"></span>Shopping Cart</a>
	</li>
	<li class="nav-item dropdown">
	  <a class="nav-link" href="{% url 'order:index' %}" class="dropdown-toggle" data-toggle="dropdown"
	     role="button" aria-expanded="false"><span class="glyphicon glyphicon-usd"></span>
	    Purchases <span class="caret"></span></a>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="{% url 'order:current' %}"><span class="glyphicon glyphicon-usd"></span>
		Current purchases</a></li>
	    <li><a href="{% url 'order:past' %}"><span class="glyphicon glyphicon-ok-circle"></span>
		Past purchases</a></li>
	  </ul>
	</li>
	<li class="dropdown nav-user">
	  <a class="nav-link" href="{% url 'order:index' %}" class="dropdown-toggle" data-toggle="dropdown"
	     role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>
	    {% firstof user.get_short_name get_full_name get_username %}
	    <span class="caret"></span></a>
	  <ul class="dropdown-menu" role="menu">
	    <li class="dropdown-header">Profile</li>
	    <li><a href="{% url 'account:profile' %}">View profile</a></li>
	    <li><a href="{% url 'account:profile_change' %}">Update profile</a></li>
	    <li class="divider"></li>
	    <li class="dropdown-header">Account</li>
	    <li><a href="{% url 'account:password_change' %}">Change password</a></li>
	    <li><a href="{% url 'account:logout' %}">Logout</a></li>
	  </ul>
	</li>

	{% else %}

	<li class="nav-item active">
	  <a class="nav-link" href="{% url 'account:register' %}?next={{ request.path }}">Register <span class="sr-only">(current)</span></a>
	</li>
	<li class="nav-item active">
	  <a class="nav-link" href="{% url 'account:login' %}?next={{ request.path }}">Log in <span class="sr-only">(current)</span></a>
	</li>
	{% endif %}
      </ul>
    </div>
  </nav>

  {% block main %}
  {# The main body #}
  {% endblock %}

  <footer>
    <hr>
    <p>Chenfan Li Moquan Jiang ece590</p>
  </footer>
</div><!--/.container -->
{% endblock %}

store/store/templates/store/home.html
{% extends "store/front-base.html" %}
{% load staticfiles %}
{% block title %}Home CFMQ{% endblock %}

{% block head %}
  <style>
    html {
      background: white url('{% static "fan.jpg"%}') no-repeat center center;
      background-size:cover;
      min-height: 100%;
    }

    body { background: none; }

    .marketing-column {
      padding: 1em 2em;
      border-radius: 6px;
      background: rgba(220, 220, 220, 0.8);
    }

    footer { display: none; }
    .footer, .footer a { color: rgba(255, 255, 255, 0.4); }
    p.admin a { color: rgba(255, 255, 255, 0.6); }

  </style>
{% endblock %}

{% block main %}
<div class="jumbotron text-center">
  <h2>CMFQ Clothes store</h2>
  <p class="lead">At CMFQ store, we have the best clothes for chenfan</p>

  <p><a class="btn btn-lg btn-success" role="button"
        href="{% url 'category:index' %}">Chenfan's clothes</a></p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <div class="marketing-column">
      <h4>Beautiful</h4>
      <p>I am beautiful</p>
      <h4>Fashion</h4>
      <p>I am fashion</p>
      <h4>Colorful</h4>
      <p>Too much clolors.</p>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="marketing-column">
      <h4>Expensive</h4>
      <p>All the products are expensive. Everyone thinks you are rich if you wear my clothes</p>
      <h4>Quality</h4>
      <p>We use the most expensive cloth</p>
      <h4>Two day free shipping over $10000</h4>
      <p>You can receie your clothes in two days!</p>
    </div>
  </div>
</div>

<div class="footer">
  <p class="pull-right">Cover photo via
    <a href="https://unsplash.com/jonasnilssonlee">Jonas Nilsson Lee</a>
    / CC0
  </p>
  <p class="pull-left admin">
    <a href="{% url 'admin:overview' %}" title="Vendor Admin Console">Vendor Console</a></p>
</div>
{% endblock %}