store/admin/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.overview, name='overview'),

    url(r'^category/', include('category_admin.urls', namespace='category')),
    url(r'^product/', include('product_admin.urls', namespace='product')),
    url(r'^account/', include('account_admin.urls', namespace='account')),
    url(r'order/', include('order_admin.urls', namespace='order')),

)

store/cart/urls.py
from django.conf.urls import patterns, url

from cart import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

store/order/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.create, name='create'),
    url(r'^current/$', views.CurrentView.as_view(), name='current'),
    url(r'^past/$', views.PastView.as_view(), name='past'),
    url(r'^(?P<order_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<order_id>\d+)/done/', views.done, name='done'),
)

store/order/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator

from product.models import Product, Photo
from cart.models import ProductItemInfo


class InvalidOrderStatusChangeException(Exception):
    """Cannot change the status of order by this way."""

    def __init__(self, order, status_from, status_to):
        self.order = order
        self.status_from = status_from
        self.status_to = status_to

    def __str__(self):
        return "Cannot change order status from %s to %s." % \
               (self.status_from, self.status_to)

class Warehouse(models.Model):
    location_x = models.IntegerField(default=0)
    location_y = models.IntegerField(default=0) 
    
class Truck(models.Model):
    truck_id = models.IntegerField(default=0)
    wh_id = models.ForeignKey(Warehouse)
    
class Inventory(models.Model):
    product_id =  models.ForeignKey(Product)
    wh_id = models.ForeignKey(Warehouse)
    open_quantity = models.IntegerField(default=0)
    

class Order(models.Model):
    """Stores recipient information and delivery status."""
    class Meta:
        ordering = ['-purchase_date']

    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('K', 'Packaging'),
        ('T', 'Ready to load'),
        ('L', 'Loading'),
        ('D', 'Loaded'),
        ('S', 'Shipping'),
        ('E', 'Delivered'),
        ('R', 'Received'),
        ('H', 'Wait for Buying'),
        ('C', 'Cancelled')
    )
    owner = models.ForeignKey(User)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')

    purchase_date = models.DateTimeField(auto_now_add=True)
    shipment_date = models.DateTimeField(null=True)

    # Stand for receipt date if status is received
    # or cancel date is status is cancelled.
    close_date = models.DateTimeField(null=True)

    recipient_name = models.CharField(max_length=255)
    recipient_address = models.CharField("address", max_length=255)
    recipient_address_2 = models.CharField("address (2th line)", max_length=255, blank=True)
    recipient_postcode = models.CharField("zip", max_length=63, blank=True)

    delivery_x = models.IntegerField(default=0)
    delivery_y = models.IntegerField(default=0)
    truck_id = models.IntegerField(null=True)
    wh_id = models.ForeignKey(Warehouse,null=True)
    tracking_num = models.IntegerField(null=True)
    
    @property
    def total_price(self):
        price = 0
        for item in self.orderitem_set.all():
            price += item.total_price
        return price

    @property
    def elapsed_days(self):
        """Return the number of days elapsed between purchase date and close date.

        None if it's not received either canceled.
        """
        if not self.close_date:
            return
        elapsed = self.close_date - self.purchase_date
        return elapsed.days

    def ship(self):
        """Ship a pending/hold order. Used by vendor."""
        assert self.shipment_date is None
        self._change_status_atomically('PH', 'S')

        self.shipment_date = timezone.now()
        self.save()

    def hold(self):
        """Hold a pending order. Used by vendor."""
        self._change_status_atomically('P', 'H')
        self.save()

    def cancel(self, operator):
        """Cancel a pending/hold order. Used by vendor/customer."""
        if operator.is_superuser:  # is vendor
            message = 'Cancelled by vendor.'
        else:
            message = 'Cancelled by customer.'
            # Only owner (and vendor) can cancel the order.
            assert self.owner == operator

        self._change_status_atomically('PH', 'C')

        self.close_date = timezone.now()
        self.save()

        self.message_set.create(content=message, by_vendor=operator.is_superuser)

    def confirm(self):
        """Confirm a shipped order. Used by customer."""
        self._change_status_atomically('KTLDES', 'R')
        self.close_date = timezone.now()
        self.save()

        # Update sale quantity and amount of products.
        for orderitem in self.orderitem_set.all():
            orderitem.product.sale_quantity += orderitem.quantity
            orderitem.product.sale_amount += orderitem.total_price
            orderitem.product.save()

    def _change_status_atomically(self, from_status, to_status):
        """Change status and commit it atomically.

        Before making change, it check whether current status is "from_status",
        if not, raise InvalidOrderStatusChangeException.
        """
        # select_for_update() must execute in non-autocommit mode.
        with transaction.atomic():

            # Using select_for_update() to lock this record.
            # It prevent other transactions acquiring locks on it (they will wait for it).

            # All status change must use _change_status_atomically() eventually,
            # so they [require a lock] -> [check status] -> [make change] -> [commit & unlock].

            # It prevent invalid status change, and satisfy requirement (H5).

            # References
            # https://docs.djangoproject.com/en/dev/ref/models/querysets/#select-for-update
            # http://stackoverflow.com/questions/1645269/concurrency-control-in-django-model

            order = Order.objects.filter(pk=self.pk).select_for_update()[0]

            if order.status != to_status:
                # Ignore redundant operation.
                # Ensure status of self is updated.
                self.status = to_status
                return
            if order.status not in from_status:
                raise InvalidOrderStatusChangeException(order, order.status, to_status)

            order.status = to_status
            order.save()

        # Update status of self.
        self.status = to_status

    def get_image(self):
        """Find the first product which has a photo in this order.
        And return it's first photo.
        """
        for item in self.orderitem_set.all():
            photos = Photo.objects.filter(product__id=item.product_id)
            if photos.exists():
                return photos[0].image

    def __str__(self):
        return "%s: %s" % (self.owner, self.get_status_display())


class OrderItem(ProductItemInfo):
    """Stores quantity and purchase price of a product for a order."""
    order = models.ForeignKey(Order)
    price = models.DecimalField(max_digits=9, decimal_places=2,
                                validators=[MinValueValidator(0)])

    
class Message(models.Model):
    """Order message, written by customer and vendor."""
    class Meta:
        ordering = ['-create_date']

    order = models.ForeignKey(Order)

    # True if it was wrote by vendor.
    # Otherwise, by customer (self.order.own).
    by_vendor = models.BooleanField(default=False)

    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)


    @property
    def writer_role(self):
        """Return 'Vendor' or 'Customer'."""
        if self.by_vendor:
            return 'Vendor'
        else:
            return 'Customer'

    @property
    def create_datetime_zone_aware(self):
        tz = timezone.get_current_timezone()
        date = self.create_date.astimezone(tz).strftime("%B %d, %Y, %H:%M:%S %Z")
        return date

store/order/forms.py
from django import forms
from django.forms import ModelForm

from .models import Order, Message


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['recipient_name', 'recipient_address',
                  'recipient_address_2', 'recipient_postcode',
                   'delivery_x','delivery_y'    ]


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea()
        }

store/order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseRedirect, \
    HttpResponseForbidden, HttpResponseBadRequest
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db import transaction
from django.views.generic import TemplateView, FormView
from rest_framework.views import APIView

from .forms import OrderForm, MessageForm
from .models import Order, InvalidOrderStatusChangeException
from account.models import Profile
from cart.utils import Cart, CannotCheckoutItemException
from store.utils import make_page


@login_required
def create(request):
    cart = Cart(request.user)

    # Check hash to ensure the cart (order) is consistent between
    # database and user's expected.
    # If it's modified in other page, redirect user to cart view to checkout again.
    cart_hash = request.GET.get('hash')
    if cart_hash is None or cart_hash != str(hash(cart)):
        messages.add_message(request, messages.WARNING,
                             "Some items have been changed, "
                             "please be prudential and checkout again.")
        return redirect('cart:index')

    # Empty cart, return.
    if not cart.item_set.all().exists():
        return redirect('cart:index')

    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():

            order = order_form.save(commit=False)
            order.owner = request.user
            try:

                # We use transaction to improve database performance and keep integrity.
                # Checkout action will rollback if any product cannot be checked out.
                with transaction.atomic():
                    order.save()
                    cart.checkout(order)
                    cart.item_set.all().delete()

            except CannotCheckoutItemException:
                # Some items are off-shelf,
                # cart.checkout() will throw this exception in the case.
                # Redirect user back to cart view.
                messages.add_message(request, messages.WARNING,
                                     "Some products are off-shelf, "
                                     "please delete them and checkout again.")
                return HttpResponseRedirect(reverse('cart:index'))

            # Remove the hash since its mission is completed.
            request.session.delete('cart-hash')
            messages.add_message(request, messages.SUCCESS,
                                 "Congratulation. Your order will be handled sooner if possible.")
            return redirect('order:detail', order.pk)
    else:
        initial = {'recipient_name': request.user.get_full_name()}
        try:
            initial['recipient_address'] = request.user.profile.address
            initial['recipient_address_2'] = request.user.profile.address_2
            initial['recipient_postcode'] = request.user.profile.postcode
        except Profile.DoesNotExist:
            pass

        order_form = OrderForm(initial=initial)

    dictionary = {'cart': cart, 'order_form': order_form,
                  'cart_hash': cart_hash}
    return render(request, 'order/create.html', dictionary)


@login_required
def index(request):
    dictionary = {'user': request.user}
    return render(request, 'order/index.html', dictionary)


class BaseOrderListView(TemplateView):
    """Show a list of certain orders.

    Used by order list for both customer and vendor, report for vendor.
    """
    template_name = 'order/list.html'
    title = 'All Purchase Orders'

    def render_to_response(self, context, **response_kwargs):
        response_kwargs['current_app'] = self.request.resolver_match.namespace
        return super().render_to_response(context, **response_kwargs)

    def get_queryset(self):
        """Return the queryset of orders. Need to be override."""
        return Order.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = make_page(self.get_queryset(),
                                      self.request.GET.get('page'))
        context['title'] = self.title
        return context


class _LoginRequiredOrderListView(BaseOrderListView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CurrentView(_LoginRequiredOrderListView):
    title = 'Current Purchase'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user,
                                             status__in=['P', 'S', 'H','K','T','L','D','S','E'])


class PastView(_LoginRequiredOrderListView):
    title = 'Past Purchase'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user,
                                             status__in=['R', 'C'])


class BaseOrderDetailView(FormView):
    form_class = MessageForm
    template_name = 'order/detail.html'
    title = 'Purchase detail'
    success_url = '.'
    vendor = False
    order = None

    def dispatch(self, request, *args, **kwargs):
        self.order = get_object_or_404(Order, pk=kwargs['order_id'])

        # Only vendor or owner of this order can view or add message.
        if not self.vendor and self.order.owner != request.user:
            return HttpResponseForbidden('This order can only be viewed by the vendor or owner.')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        message = form.save(commit=False)
        message.order = self.order
        message.by_vendor = self.vendor
        message.save()

        messages.add_message(self.request, messages.SUCCESS,
                             "Message has been added.")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = self.order
        context['order_messages'] = self.order.message_set.all()
        context['vendor'] = self.vendor
        context['title'] = self.title
        return context


class DetailView(BaseOrderDetailView):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@login_required
def done(request, order_id):
    """Shown after order is confirmed by customer."""
    order = get_object_or_404(Order, pk=order_id)

    if order.status != 'R':
        return HttpResponseRedirect(reverse('order:detail', args=[order_id]))

    dictionary = {'order': order}
    return render(request, 'order/done.html', dictionary)


class OrderView(APIView):
    def put(self, request, order_id):
        order = get_object_or_404(Order, pk=order_id)

        if not request.user.is_authenticated():
            return HttpResponseForbidden('No login.')

        vendor = request.user.is_staff
        if request.user != order.owner and not vendor:
            return HttpResponseForbidden('Permission denied to access this order.')

        new_status = request.data.get('status')
        if new_status is None:
            return HttpResponseBadRequest('Lack argument "status".')

        # If it has already been this status, just return ok.
        if order.status == new_status:
            return HttpResponse(status=204)

        try:
            # Cancel this order.
            if new_status == 'C':
                order.cancel(operator=request.user)

            # Confirm Received, only customer.
            elif new_status == 'R':
                if vendor and request.user != order.owner:
                    return HttpResponseForbidden('Only customer can do it.')
                order.confirm()

            # Hold this order, only vendor.
            elif new_status == 'H':
                if not vendor:
                    return HttpResponseForbidden('Only vendor can do it.')
                order.hold()

            # Ship this order, only vendor.
            elif new_status == 'S':
                if not vendor:
                    return HttpResponseForbidden('Only vendor can do it.')
                order.ship()

        except InvalidOrderStatusChangeException:
            return HttpResponseForbidden('Wrong status.')

        return HttpResponse(status=204)

store/order/templates/order/create.html
{% extends "store/front-base.html" %}
{% load bootstrap3 %}
{% block title %}New Order{% endblock %}

{% block main %}
  <h1>Checkout</h1>

  <div class="row">
    <div class="col-md-12">
      <h2>Order Detail</h2>

      {% include 'order/item-list.html' with items=cart.item_set.all %}

      <p>Total price: ${{ cart.total_price }}</p>

      <p><a href="{% url 'cart:index' %}"
       title="Shopping Cart">Back to shopping cart</a>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-lg-5 col-sm-12">
      <h2>Shipping Information</h2>

      <form name="order" method="post"
            action="{% url 'order:create' %}?hash={{ cart_hash }}">
        {% csrf_token %}
        {% bootstrap_form order_form %}

        {% buttons %}
          <button type="submit" class="btn btn-primary">Checkout</button>
        {% endbuttons  %}
      </form>
      </div>
  </div>

{% endblock %}

store/order/templates/order/detail.html
{% extends "store/front-base.html" %}
{% block title %}Purchase detail{% endblock %}

{% block main %}

  {% include 'order/detail_base.html' %}

{% endblock %}

store/order/templates/order/detail_base.html
<h1 class="page-header">Purchase Detail</h1>

<div class="row">
  <div id="order-status-box" class="col-md-6 col-lg-5">
    <p><span class="item-name">Status</span>{{ order.get_status_display }}</p>
    <p><span class="item-name">Purchase on</span>{{ order.purchase_date }}</p>
    {% if order.shipment_date %}
    <p><span class="item-name">Shipment on</span>{{ order.shipment_date }}</p>
    {% endif %}
    {% if order.tracking_num  %}
    <p><span class="item-name">Tracking number</span>{{ order.tracking_num }}</p>
    {% endif %}

    {% if vendor %}
      {% if order.status == 'P' %}{# Pending #}
    {% elif order.status == 'H' %}{# Holding #}
    {% endif %}
    {% else %}
      {% if order.status == 'E' and not vendor %} {# Shiping #}
        <button data-url="{% url 'order_api:order' order.pk %}"
                class="confirm-order btn btn-block btn-primary">Received Confirm</button>
      {% endif %}
    {% endif %}

    {% if order.status in 'PH' %}
      <button data-url="{% url 'order_api:order' order.pk %}"
          class="cancel-order btn btn-block btn-danger">Cancel</button>
    {% endif %}
  </div>

  <div id="order-recipient-box" class="col-md-6 col-lg-7">
    <p><span class="item-name">Order ID</span>#{{ order.pk }}</p>
    <p><span class="item-name">Recipient</span>{{ order.recipient_name }}</p>
    <p><span class="item-name">Address</span>{{ order.recipient_address }}</p>
    {% if order.recipient_address_2 %}
    <p><span class="item-name">Address 2</span>{{ order.recipient_address_2 }}</p>
    {% endif %}
    {% if order.recipient_postcode %}
    <p><span class="item-name">Postcode</span>{{ order.recipient_postcode }}</p>
    {% endif %}
  </div>

</div>



<div class="row">
  <div id="order-items" class="col-md-12">
    <h2>Products</h2>
    {% include 'order/item-list.html' with items=order.orderitem_set.all %}
    <p class="pull-right">Total amount: <span class="price">${{ order.total_price }}</span></p>
  </div>

</div>

<div class="row standalone-title">
  <div class="col-md-12">
    <h2>Messages</h2>
  </div>
</div>

<div class="row">

  <div class="col-md-5">
    <form name="message" method="post" action=".">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_content">Context</label>
        <textarea id="id_content" class="form-control" rows="3" name="content"></textarea>
      </div>
      <button type="submit" class="btn btn-default pull-right"><span class="glyphicon glyphicon-envelope"></span>
        Send</button>
    </form>
  </div>

  <div class="col-md-7">
    <ul id="order-messages" class="common-list">
      {% for message in order_messages %}
        <li>
          <h4>
            <span class="role">{{ message.writer_role }}</span>
            <small>
              <span class="glyphicon glyphicon-time"></span>
              {{ message.create_datetime_zone_aware }}
            </small>
          </h4>
          <p class="content">{{ message.content }}</p>
        </li>
      {% endfor %}
    </ul>
  </div>

</div>


<script>
// TODO: put into separated js file.

function set_status(url, status, callback) {
  $.ajax({
    url: url,
    type: 'PUT',
    data: {'status': status}
  }).done(function () {
    if (callback == undefined) {
      location.reload();
    } else {
      callback();
    }
  });
}

$('button.cancel-order').click(function () {
  if (!confirm('This order will be canceled permanently.')) {
    return;
  }
  set_status($(this).data('url'), 'C');
});

$('button.confirm-order').click(function () {
  if (!confirm("This order will be marked as finished. " +
      "If you haven't received all items, please click cancel.")) {
    return;
  }
  set_status($(this).data('url'), 'R', function () {
    window.location.href = 'done/';
  });
});

$('button.hold-order').click(function () {
  set_status($(this).data('url'), 'H');
});

$('button.ship-order').click(function () {
  set_status($(this).data('url'), 'S');
});

</script>

store/order/templates/order/done.html
{% extends "store/front-base.html" %}
{% block title %}Purchase Done{% endblock %}

{% block main %}
  <h1>Thank You</h1>

  <p>Your purchase has being done.</p>

  <ul>
  {% for item in order.orderitem_set.all %}
    <li>
      {{ item.name }}
      <a href="{% url 'product:detail' item.product.pk %}#rating">View / Rating</a>
    </li>
  {% endfor %}
  </ul>

{% endblock %}

store/order/templates/order/index.html
{% extends "store/front-base.html" %}
{% block title %}Purchase tracking{% endblock %}

{% block main %}
  <h1 class="page-header">Purchase Orders</h1>
  <div class="row">
    <div class="col-md-6">

      <div class="list-group">
        <a href="{% url 'order:current' %}" class="list-group-item">
          <h4 class="list-group-item-heading">Current purchases</h4>
          <p class="list-group-item-text">Show all the purchase orders that you has placed,
          but has not received or cancelled.</p>
        </a>
        <a href="{% url 'order:past' %}" class="list-group-item">
          <h4 class="list-group-item-heading">Past purchases</h4>
          <p class="list-group-item-text">Show all the fulfilled or cancelled purchase orders.</p>
        </a>
      </div>
    </div>
  </div>

{% endblock %}

store/order/templates/order/item-list.html
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
      <tr class="order-item">
        <td><a href="{% url 'product:detail' item.product.id %}">{{ item.name }}</a></td>
        <td>${{ item.price }}</td>
        <td>{{ item.quantity }}</td>
        <td>${{ item.total_price }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

store/order/templates/order/list.html
{% extends "store/front-base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block main %}
  <h1 class="page-header">{{ title }}</h1>

  <div class="row">
    <div class="col-md-12">
      {% include 'order/order_list.html' with list_item='order/order_list_item.html' %}
    </div>
  </div>

{% endblock %}

store/order/templates/order/order_list.html
{% load thumbnail %}

<ul id="order-list" class="common-list">
{% for order in orders %}
  <li class="row">

    <div class="col-thumbnail col-md-2">
      <div class="thumbnail">
      {% thumbnail order.get_image "96x96" crop="center" as im %}
        <img src="{{ im.url }}"
           width="{{ im.width }}" height="{{ im.height }}">
      {% empty %}
        <div class="placeholder">
          <span>No Image</span>
        </div>
      {% endthumbnail %}
      </div>
    </div>
      {% include list_item %}
    <hr>
  </li>
{% empty %}
  No purchase orders.
{% endfor %}
</ul>

{% if orders %}
{% include 'store/common-pagination.html' with list=orders %}
{% endif %}

store/order/templates/order/order_list_item.html
<div class="col-md-8 items">
  <p><span class="item-name">Purchase date:</span>
    <span class="date">{{ order.purchase_date }}</span></p>
  <p><span class="item-name">Status:</span>
    <span class="status">{{ order.get_status_display }}</span></p>
  <p><span class="item-name">Total amount:</span>
    <span class="price">${{ order.total_price|floatformat:2 }}</span></p>
</div>

<div class="col-md-2">
  <a class="btn btn-default btn-block" role="button"
     href="{% url 'order:detail' order.pk %}">View detail</a>
</div>