store/account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from . import views
from .forms import PasswordChangeForm

urlpatterns = patterns(
    '',
    url(r'^login/$', auth_views.login, name='login',
        kwargs={'template_name': 'account/login.html'}),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'template_name': 'account/logged_out.html'}),
    url(r'^password_change/$', auth_views.password_change, name='password_change',
        kwargs={'template_name': 'account/password_change.html',
                'post_change_redirect': 'done/',
                'password_change_form': PasswordChangeForm}),
    url(r'^password_change/done/$', auth_views.password_change_done,
        name='password_change_done',
        kwargs={'template_name': 'account/password_change_done.html'}),

    url(r'^profile/$', views.profile, name='profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/done/$', views.register_done, name='register_done'),
    url(r'^profile/update/$', views.profile_change, name='profile_change'),
)

store/admin/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.overview, name='overview'),

    url(r'^category/', include('category_admin.urls', namespace='category')),
    url(r'^product/', include('product_admin.urls', namespace='product')),
    url(r'^account/', include('account_admin.urls', namespace='account')),
    url(r'order/', include('order_admin.urls', namespace='order')),

)

store/cart/urls.py
from django.conf.urls import patterns, url

from cart import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

store/category/urls.py
from django.conf.urls import patterns, url

from category import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<category_id>\d+)/$', views.DetailView.as_view(), name='detail')
)

store/category/models.py
from django.db import models


class Category(models.Model):
    """Product category with optional description."""
    name = models.CharField('Category Name', max_length=255)
    description = models.TextField(null=True)

    def get_cover_image(self):
        """
        Return the front cover image, which is selected from
        one of product photo in this category.

        May return None if no front cover.
        """
        from product.models import Photo

        photos = Photo.objects.filter(product__category__id=self.pk)
        if photos.exists():
            return photos[0].image

    def __str__(self):
        return self.name

store/category/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView

from .models import Category
from store.utils import make_page


class IndexView(TemplateView):
    template_name = 'category/index.html'

    def render_to_response(self, context, **response_kwargs):
        # Set current_app so that url() on template can render correctly.
        # https://docs.djangoproject.com/en/1.7/topics/http/urls/#topics-http-reversing-url-namespaces
        response_kwargs['current_app'] = self.request.resolver_match.namespace

        return super().render_to_response(context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = Category.objects.all()
        context['categories'] = categories
        return context


class DetailView(TemplateView):
    template_name = 'category/detail.html'
    order_fields = ('price', '-price', 'average_rating', '-average_rating')

    def render_to_response(self, context, **response_kwargs):
        response_kwargs['current_app'] = self.request.resolver_match.namespace
        return super().render_to_response(context, **response_kwargs)

    def get_queryset(self, category):
        return category.product_set.exclude(status='F')  # exclude off-shelf

    def get_context_data(self, category_id, **kwargs):
        context = super().get_context_data(**kwargs)

        category = get_object_or_404(Category, pk=category_id)
        name_filter = self.request.GET.get('filter', '')
        sort = self.request.GET.get('sort')

        products = self.get_queryset(category)
        if name_filter:
            products = products.filter(name__contains=name_filter)
        if sort in self.order_fields:
            products = products.order_by(sort)
        else:
            sort = ''

        context['category'] = category
        context['filter'] = name_filter
        context['sort'] = sort

        products = make_page(products, self.request.GET.get('page'))
        context['products'] = products

        return context

store/category/templates/category/category_list.html
{% load thumbnail %}

{% for category in categories %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      {% thumbnail category.get_cover_image "290x193" crop="center" as im %}
        <img src="{{ im.url }}" alt="cover photo">
      {% empty %}
        <div class="placeholder">
          <span>No Image</span>
        </div>
      {% endthumbnail %}
      <div class="caption">
        <h3>{{ category.name }}</h3>
        <p>{{ category.description }}</p>
        <p>{% include buttons %}</p>
      </div>
    </div>
  </div>
{% endfor %}

store/category/templates/category/category_list_buttons.html
<a href="{% url 'category:detail' category.id %}"
  class="btn btn-primary" role="button">Show all</a>

store/category/templates/category/detail.html
{% extends "store/front-base.html" %}
{% block title %}{{ category }} - Category{% endblock %}

{% block main %}

  <h1 class="page-header">{{ category }}
    <small>All products</small>
  </h1>
  <p>{{ category.description }}</p>

  {% include 'category/product_list.html' with list_item='category/product_list_item.html' %}

{% endblock %}

store/category/templates/category/index.html
{% extends "store/front-base.html" %}
{% block title %}Categories{% endblock %}

{% block main %}

  <h1 class="page-header">Categories</h1>
  <div class="row" id="category-list">
    {% include 'category/category_list.html' with buttons='category/category_list_buttons.html' %}
  </div>

{% endblock %}

store/category/templates/category/product_list.html
{% load thumbnail %}

<div class="row">

  <div class="col-md-12">
    <form action="." method="GET" name="filter" class="form-inline">
      <input name="filter" type="search" class="form-control" autocomplete="on"
             placeholder="Product name" value="{{ filter }}">
      <input type="hidden" name="sort" value="{{ sort }}">
      <input type="hidden" name="page" value="{{ products.number }}">
      <button type="submit" class="btn btn-default">Filter</button>
      {% if filter %}
        <button id="filter-reset" class="btn btn-default">Clear</button>
      {% endif %}
    </form>

    <script>
      $(document).ready(function () {
        $('#filter-reset').click(function () {
          $('input[name="filter"]').val('');
          $('form[name="filter]').submit();
        });
      });
    </script>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="btn-group" role="group" >
      <a role="button" class="btn btn-default {% if not sort %}active{% endif %}"
          href="?filter={{ filter }}&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort"></span> Default</a>
      <a role="button" class="btn btn-default {% if sort == 'price' %}active{% endif %}"
          href="?filter={{ filter }}&sort=price&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort-by-order"></span> Price</a>
      <a role="button" class="btn btn-default {% if sort == '-price' %}active{% endif %}"
          href="?filter={{ filter }}&sort=-price&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort-by-order-alt"></span> Price</a>
      <a role="button" class="btn btn-default {% if sort == '-average_rating' %}active{% endif %}"
          href="?filter={{ filter }}&sort=-average_rating&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort-by-attributes-alt"></span> Rating</a>
      {% if vendor %}
      <a role="button" class="btn btn-default {% if sort == '-sale_quantity' %}active{% endif %}"
          href="?filter={{ filter }}&sort=-sale_quantity&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort-by-attributes-alt"></span> Sales quantity</a>
      <a role="button" class="btn btn-default {% if sort == '-sale_amount' %}active{% endif %}"
          href="?filter={{ filter }}&sort=-sale_amount&page={{ products.number }}"><span class="glyphicon
          glyphicon-sort-by-attributes-alt"></span> Sales amount</a>
      {% endif %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ul id="product-list" class="common-list">
      {% for product in products %}
        <li class="row">
          {% include list_item %}
          <hr>
        </li>
      {% empty %}
        (no related product)
      {% endfor %}
    </ul>
  </div>
</div>

{% include 'store/common-pagination.html' with list=products %}

store/category/templates/category/product_list_item.html
{% load thumbnail %}

<div class="col-thumbnail col-md-2">
  <div class="thumbnail">
  {% thumbnail product.get_image "96x96" crop="center" as im %}
    <img src="{{ im.url }}"
       width="{{ im.width }}" height="{{ im.height }}">
  {% empty %}
    <div class="placeholder">
      <span>No Image</span>
    </div>
  {% endthumbnail %}
  </div>
</div>

<div class="col-md-10">
  <a href="{% url 'product:detail' product.id %}"><h3>{{ product.name }}</h3></a>

  <div class="product-detail row-fluid">
    <div class="col-md-3">
      <p><span class="price">${{ product.price }}</span>
        {% if not product.in_stock %}
          <span class="label label-warning">Out of stock</span>
        {% endif %}
      </p>
      {% if product.average_rating %}
        <p><span title="Rated by {{ product.rating_set.count }} customers"
            class="rating">{{ product.get_average_rating_display }}
          <sup>{{ product.average_rating }}</sup></span></p>
      {% endif %}
    </div>
    <div class="col-md-2 col-md-offset-7">
      {% if user.is_authenticated %}
      <button class="btn btn-default btn-block buy"
          data-link="{% url 'cart_api:item' product.id %}">Buy now</button>
      {% else %}
      <a class="btn btn-default btn-block" role="button"
          href="{% url 'account:login' %}?next={{ request.path }}">Buy now</a>
      {% endif %}

      <a class="btn btn-default btn-block" role="button"
         href="{% url 'product:detail' product.id %}">View detail</a>
    </div>
  </div>

</div>