store/account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from . import views
from .forms import PasswordChangeForm

urlpatterns = patterns(
    '',
    url(r'^login/$', auth_views.login, name='login',
        kwargs={'template_name': 'account/login.html'}),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'template_name': 'account/logged_out.html'}),
    url(r'^password_change/$', auth_views.password_change, name='password_change',
        kwargs={'template_name': 'account/password_change.html',
                'post_change_redirect': 'done/',
                'password_change_form': PasswordChangeForm}),
    url(r'^password_change/done/$', auth_views.password_change_done,
        name='password_change_done',
        kwargs={'template_name': 'account/password_change_done.html'}),

    url(r'^profile/$', views.profile, name='profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/done/$', views.register_done, name='register_done'),
    url(r'^profile/update/$', views.profile_change, name='profile_change'),
)

store/admin/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.overview, name='overview'),

    url(r'^category/', include('category_admin.urls', namespace='category')),
    url(r'^product/', include('product_admin.urls', namespace='product')),
    url(r'^account/', include('account_admin.urls', namespace='account')),
    url(r'order/', include('order_admin.urls', namespace='order')),

)

store/cart/urls.py
from django.conf.urls import patterns, url

from cart import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

store/product/urls.py
from django.conf.urls import patterns, url

from product import views

urlpatterns = patterns(
    '',
    url(r'^(?P<product_id>\d+)/$', views.detail, name='detail')
)

store/product/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField

from category.models import Category


RATING_DISPLAY = ('Horrible', 'Bad', 'Fair', 'Good', 'Fantastic')


class Product(models.Model):

    STATUS_CHOICES = (
        ('N', 'In stock'),
        ('O', 'Out of stock'),
        ('F', 'Off shelf')
    )

    name = models.CharField('Product name', max_length=255)
    price = models.DecimalField('Price ($)', max_digits=9, decimal_places=2,
                                validators=[MinValueValidator(0)])
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    category = models.ForeignKey(Category)
    description = models.TextField(blank=True)

    # Cache the total sale quantity and amount, re-calculate
    # once any order include this product is confirmed.
    sale_quantity = models.IntegerField(default=0)
    sale_amount = models.DecimalField(default=0, max_digits=12, decimal_places=2)

    # Cache the average rating, re-calculate once any user change the rating.
    Product_num = models.FloatField("Product number", default=0, editable=False)

    # Router specified properties:

    Material = models.CharField('Material', max_length=127, blank=True)
    # e.g. Atheros AR9344. Blank value stands for unknown.

    Style = models.CharField('Style', max_length=127, blank=True)
    # e.g. AR9344. Blank value stands for unknown.

    Shoulder = models.IntegerField("Shoulder",default=0,
                                    validators=[MinValueValidator(1)])
    Waist = models.IntegerField('Waist',default=0,
                                    validators=[MinValueValidator(0)])
    Chest = models.IntegerField('Chest', default=0,
                                    validators=[MinValueValidator(0)])
    Fashion_element = models.CharField(max_length=127, blank=True)
    # e.g. 802.11b/g/n/ac. Blank value stands for not supported.

    Picture  = models.CharField(max_length=127, blank=True)
    # e.g. 12 VDC, 2 A. Blank value stands for unknown.

    Has_waitband = models.BooleanField('Has waistband', default=False)

    @property
    def in_stock(self):
        return self.status == 'N'

    @property
    def off_shelf(self):
        return self.status == 'F'

    def update_rating(self):
        """Re-calculate the average rating and update the rating field."""
        total = 0
        count = 0
        for rating in self.rating_set.all():
            total += rating.point
            count += 1
        self.average_rating = total / count
        self.save()

    def get_average_rating_display(self):
        if 1 <= self.average_rating <= 5:
            return RATING_DISPLAY[round(self.average_rating) - 1]

    def has_bought_by_user(self, user):
        """Return True if this user has purchased it and confirmed the order."""
        orders = user.order_set.filter(status='R')
        for order in orders:
            if order.orderitem_set.filter(product=self).exists():
                return True
        return False

    def get_image(self):
        try:
            print(self.photo_set.all()[0].image)
            return self.photo_set.all()[0].image
        except Photo.DoesNotExist:
            pass

    def __str__(self):
        return self.name


class Photo(models.Model):
    """Photos of product.

    Each product may have one or more photos.
    Each photo has an image file and an optional description.
    """
    product = models.ForeignKey(Product, null=True)
    image = ImageField(upload_to='photos/%Y/%m')
    description = models.CharField(max_length=255, null=True)
    # TODO: Maintain the display order of photos (#E7)

    # Delete image file when photo is removed. Not useful, having been implemented by inlineformset
    # Can be better implemented by pre_delete signal
    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        # Delete the model before the file
        super(Photo, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)


class Rating(models.Model):
    """User's rating for a product.

    Point is between (both include) 1 to 5.
    """
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    point = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

store/product/forms.py
from django import forms

from .models import Rating


RATING_CHOICES = (
    (1, '1 Horrible'),
    (2, '2 Bad'),
    (3, '3 Fair'),
    (4, '4 Good'),
    (5, '5 Fantastic')
)


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['point']
        widgets = {
            'point': forms.RadioSelect(choices=RATING_CHOICES),
        }

    def clean_point(self):
        point = self.cleaned_data.get('point')
        if point not in (1, 2, 3, 4, 5):
            raise forms.ValidationError('Point must be chosen from 1 to 5.',
                                        code='invalid-point')
        return point

    def clean(self):
        cleaned_data = super().clean()

        if not self.instance.product.has_bought_by_user(self.instance.user):
            raise forms.ValidationError('Cannot rate before buying it.',
                                        code='no-purchase-yet')
        return cleaned_data

store/product/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import HttpResponseRedirect
from django.contrib import messages

from .models import Product, Rating
from .forms import RatingForm


@ensure_csrf_cookie
def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    # Handle rating.
    rating = None
    if request.user.is_authenticated():
        try:
            rating = request.user.rating_set.get(product=product)
        except Rating.DoesNotExist:
            if product.has_bought_by_user(request.user):
                rating = Rating(product=product, user=request.user)

    if request.method == 'POST':
        rating_form = RatingForm(request.POST, instance=rating)

        if rating_form.is_valid():
            rating_form.save()
            product.update_rating()

            messages.add_message(request, messages.SUCCESS,
                                 "Thanks for your rating.")
            # Refresh page to prevent duplicate submission
            return HttpResponseRedirect('.')

    else:
        if rating is not None:
            rating_form = RatingForm(instance=rating)
        else:
            rating_form = None

    dictionary = {'product': product,
                  'rating_form': rating_form}
    if product.off_shelf:
        return render(request, 'product/off-shelf.html', dictionary, status=404)
    else:
        return render(request, 'product/detail.html', dictionary)

store/product/templates/product/detail.html
{% extends "store/front-base.html" %}
{% load thumbnail %}

{% block title %}{{ product }} - Product{% endblock %}

{% block main %}

  <h1 class="page-header">{{ product.name }}
    <small>{{ product.category }}
      <a class="category-link" title="View all {{ product.category }}"
         href="{% url 'category:detail' product.category.id %}">
        <span class="glyphicon glyphicon-th-list"></span>
      </a>
    </small>
  </h1>

  <div class="row">

    {% if product.photo_set.exists %}
    <div class="col-md-5 col-lg-4">
      <div id="carousel-thumbnail" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          {% for photo in product.photo_set.all %}
          <li data-target="#carousel-thumbnail" data-slide-to="{{ forloop.counter0 }}"
              {% if forloop.first %}class="active"{% endif %}></li>
          {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          {% for photo in product.photo_set.all %}
          <div class="item{% if forloop.first %} active{% endif %}">
            {% thumbnail photo.image "384x256" crop="center" as im %}
            <a href="{{ photo.image.url }}" title="Click for large picture">
              {# TODO: Open large picture in a user friendly way. #}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                  alt="Thumbnail image {{ forloop.counter }}" title="{{ photo.description }}">
            </a>
            {% endthumbnail %}
            <div class="carousel-caption">
              {{ photo.description }}
            </div>
          </div>
          {% endfor %}
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-thumbnail" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-thumbnail" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    {% endif %}

    <div class="col-md-7 col-lg-8">
      <div class="showcase">
        <p><span class="item-name">Price:</span>
          <span class="price">${{ product.price|floatformat:2 }}</span></p>

        <p><span class="item-name">Status:</span>
        {% if product.in_stock %}
          <span class="in-stock">In stock</span>
        {% else %}
          <span class="out-of-stock">Out of stock</span>
        {% endif %}
        </p>

        <p><span class="item-name">Rating:</span>
          {% if product.average_rating %}
            <span class="rating point-{{ product.average_rating|floatformat:0 }}">{{ product.get_average_rating_display }}</span>
            <small>({{ product.average_rating|floatformat }} out of 5 points,
              by {{ product.rating_set.count }} customers)</small>
          {% else %}
            <small>(no data)</small>
          {% endif  %}
        </p>

        <p class="pull-right">
          {% if rating_form %}
            <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#modal-rating">
              <span class="glyphicon glyphicon-star"></span>
              Rating
            </button>
          {% endif %}
          {% if user.is_authenticated %}
          <button class="btn btn-primary btn-lg buy"
            data-link="{% url 'cart_api:item' product.id %}"><span class="glyphicon glyphicon-shopping-cart"></span>
          Add to Cart</button>
          {% else %}
          <a class="btn btn-primary btn-lg" role="button"
            href="{% url 'account:login' %}?next={{ request.path }}"><span class="glyphicon glyphicon-shopping-cart"></span>
          Add to Cart</a>
          {% endif %}
        </p>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-5 col-lg-4">
      <h3>Properties</h3>
      <table class="table table-striped">
        <tbody>
          {% if product.Product_num %}
          <tr>
            <td>Product number</td>
            <td>{{ product.Product_num }}</td>
          </tr>
          {% endif %}
          {% if product.Material %}
          <tr>
            <td>Material</td>
            <td>{{ product.Material }}</td>
          </tr>
          {% endif %}
          <tr>
            <td>Style</td>
            <td>{{ product.Style }} </td>
          </tr>
          <tr>
            <td>Shoulder</td>
            <td>{{ product.Shoulder }} cm</td>
          </tr>
          <tr>
            <td>Waist</td>
            <td>{{ product.Waist }} cm</td>
          </tr>
          {% if product.Chest%}
          <tr>
            <td> Chest</td>
            <td>{{ product.Chest }} cm</td>
          </tr>
          {% endif %}
          {% if product.Fashion_element %}
          <tr>
            <td>Fashion element</td>
            <td>{{ product.Fashion_element }}</td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>

    <div class="col-md-7 col-lg-8">
      <h3>Description</h3>
      {% if product.description %}
        <p>{{ product.description }}</p>
      {% else %}
        <p>No description for this product.</p>
      {% endif %}
    </div>

  </div>

  {% if rating_form %}
  <div class="modal fade" id="modal-rating" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="ratingModalLabel">Rating</h4>
        </div>
        <div class="modal-body">
          <p>Please select your feel to this product.</p>

          <form id="rating" method="POST" action=".">{% csrf_token %}
            {{ rating_form.point }}
          </form>
            Your rating may be shown to other customers anonymously and you can change it future.</p>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" form="rating">Save</button>
        </div>
      </div>
    </div>
  </div>
  <script>
  // Hacking to add stars in rating form.
  var $star = $('<span>').addClass('glyphicon').addClass('glyphicon-star');
  $('#id_point').find('label').each(function (index) {
    var $stars = $('<div>').addClass('stars');
    for (var i=0; i<index+1; ++i) {
      $star.clone().appendTo($stars);
    }
    $(this).append($stars);
  });
  </script>
  {% endif %}

{% endblock %}

store/product/templates/product/off-shelf.html
{% extends "store/front-base.html" %}
{% block title %}Product Not Found{% endblock %}

{% block main %}

  <h1>Product Not Found</h1>
  <p>Sorry, this product is off-shelf.</p>

{% endblock %}